import{a as E,S as q,i as n}from"./assets/vendor-CIu9XFSi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",B="52857453-560792bcb66dbe1ba9d4bb66c";async function g(o,t=1){const s={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await E.get(P,{params:s})).data}catch(a){throw console.error("Pixabay API error:",a),a}}const h=document.querySelector(".gallery"),c=document.querySelector(".js-load-more"),p=document.querySelector("#loader");let m;function b(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),y(),m?m.refresh():m=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){h.innerHTML=""}function L(){p.classList.remove("hidden")}function w(){p.classList.add("hidden")}function y(){c.classList.remove("load-more-hidden"),c.classList.add("load-more")}function d(){c.classList.add("load-more-hidden"),c.classList.remove("load-more")}const $=document.querySelector(".form"),A=document.querySelector(".js-load-more");let l="",u=1,f=0;const I=15;$.addEventListener("submit",O);A.addEventListener("click",x);async function O(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){n.warning({title:"Warning",message:"Please enter a search term."});return}u=1,M(),d(),L();try{const t=await g(l,u);if(f=t.totalHits,t.hits.length===0){n.info({title:"No results",message:"No images found. Try another keyword."});return}b(t.hits),f>I?y():(d(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong while fetching images."})}finally{w()}}async function x(){d(),u+=1,L();try{const o=await g(l,u);b(o.hits),H(),document.querySelectorAll(".gallery-item").length<f?y():(d(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Failed to load more images."})}finally{w()}}function H(){var s;const o=(s=document.querySelector(".gallery"))==null?void 0:s.firstElementChild;if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
