import{a as q,S as E,i}from"./assets/vendor-CIu9XFSi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",M="52857453-560792bcb66dbe1ba9d4bb66c";async function f(o,t=1){const s={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await q.get(B,{params:s})).data}catch(a){throw console.error("Pixabay API error:",a),a}}const y=document.querySelector(".gallery"),c=document.querySelector(".js-load-more"),g=document.querySelector("#loader");let u;function h(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),L(),u?u.refresh():u=new E(".gallery a",{captionsData:"alt",captionDelay:250})}function P(){y.innerHTML=""}function p(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}function L(){c.classList.remove("load-more-hidden"),c.classList.add("load-more")}function w(){c.classList.add("load-more-hidden"),c.classList.remove("load-more")}const $=document.querySelector(".form"),A=document.querySelector(".js-load-more");let l="",d=1,m=0;$.addEventListener("submit",I);A.addEventListener("click",O);async function I(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search term."});return}d=1,P(),w(),p();try{const t=await f(l,d);if(m=t.totalHits,t.hits.length===0){i.info({title:"No results",message:"No images found. Try another keyword."});return}h(t.hits),m>15&&L()}catch{i.error({title:"Error",message:"Something went wrong while fetching images."})}finally{b()}}async function O(){d+=1,p();try{const o=await f(l,d);h(o.hits),x(),document.querySelectorAll(".gallery-item").length>=m&&(w(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Failed to load more images."})}finally{b()}}function x(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
